CREATE database mergedatabase;
USE mergedatabase;

CREATE USER 'merge_connect'@'%' 
	IDENTIFIED VIA mysql_native_password USING '?tc,L2D8Y4t]';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, 
	CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, 
	ALTER ROUTINE, EXECUTE 
ON *.* TO 'merge_connect'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES
ON `mergedatabase`.* TO 'merge_connect'@'%';